name: NathalieChikhi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75466
title: Artwork of the artist Nathalie Chikhi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8d735f'
    - '#5e280f'
    - '#fa59a3'
    - '#68d0d7'
  brandStrength: 1
  lightness: 0.27531034243293107
  saturation: 0.28824928239919245
  rhythmicContrast: 0.9031965965405107
purpose: []
