name: NathalieChikhi
favicon: null
layout_spectrum: 0.7492162073031068
typography_spectrum: 0.6439935259986669
title: Artwork of the artist Nathalie Chikhi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cab9aa'
    - '#8c7760'
    - '#522939'
    - '#eb2c67'
  brandStrength: 0.5
  lightness: 0.27531034243293107
  saturation: 0.28824928239919245
  rhythmicContrast: 0.9031965965405107
purpose: []
